name: dw4_movies_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  flutter_rating_stars: ^1.0.3+4
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: FilmesAppIcons
      fonts:
        - asset: assets/fonts/FilmesAppIcons.ttf

    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf